import type { AuditLogItem } from "@/types/auth";
import { UserRole } from "@/types/auth";

/** Mock 数据（未登录时展示用） */
export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 1,
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    userId: 1,
    username: "admin",
    role: UserRole.ADMIN,
    source: "web",
    action: "login",
    resource: "user",
    method: "POST",
    success: true,
    ip: "192.168.1.100",
    status: 200,
    durationMs: 125,
  },
  {
    id: 2,
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    userId: 2,
    username: "operator",
    role: UserRole.OPERATOR,
    source: "web",
    action: "execute",
    resource: "deployment",
    method: "POST",
    success: true,
    ip: "192.168.1.101",
    status: 200,
    durationMs: 342,
  },
  {
    id: 3,
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    userId: 3,
    username: "viewer",
    role: UserRole.VIEWER,
    source: "api",
    action: "read",
    resource: "pod",
    method: "GET",
    success: false,
    ip: "192.168.1.102",
    status: 403,
    durationMs: 15,
  },
  {
    id: 4,
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    userId: 1,
    username: "admin",
    role: UserRole.ADMIN,
    source: "web",
    action: "create",
    resource: "user",
    method: "POST",
    success: true,
    ip: "192.168.1.100",
    status: 201,
    durationMs: 89,
  },
  {
    id: 5,
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    userId: 2,
    username: "operator",
    role: UserRole.OPERATOR,
    source: "api",
    action: "execute",
    resource: "pod",
    method: "POST",
    success: true,
    ip: "192.168.1.101",
    status: 200,
    durationMs: 1250,
  },
  {
    id: 6,
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    userId: 0,
    username: "guest",
    role: 0,
    source: "web",
    action: "login",
    resource: "user",
    method: "POST",
    success: false,
    ip: "10.0.0.50",
    status: 401,
    durationMs: 45,
  },
];
