apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-metrics
  namespace: test
  labels:
    app: test-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-metrics
  template:
    metadata:
      labels:
        app: test-metrics
    spec:
      nodeSelector:
        kubernetes.io/hostname: raspi-one

      securityContext:
        runAsUser: 0
      containers:
        - name: test-metrics
          image: bukahou/atlhyper-metrics:test
          imagePullPolicy: Always

          securityContext:
            privileged: true # ✅ 允许访问 /proc /sys
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PROC_ROOT
              value: /hostproc
            - name: SYS_ROOT
              value: /hostsys
            - name: ROOT_PATH
              value: /host_root
            - name: PUSH_ENABLE
              value: "true"
            - name: AGENT_SVC_NAME
              value: "192.168.0.117"
            - name: AGENT_SVC_PORT
              value: "8082"
            - name: INGEST_PATH
              value: "/ingest/metrics/v1/snapshot"
            - name: PUSH_INTERVAL
              value: "5s"
            - name: PUSH_TIMEOUT
              value: "5s"

          volumeMounts:
            - name: proc-volume
              mountPath: /hostproc
              readOnly: true
            - name: sys-volume
              mountPath: /hostsys
              readOnly: true
            - name: root-volume
              mountPath: /host_root
              readOnly: true

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

      volumes:
        - name: proc-volume
          hostPath:
            path: /proc
            type: Directory
        - name: sys-volume
          hostPath:
            path: /sys
            type: Directory
        - name: root-volume
          hostPath:
            path: /
            type: Directory
